# Generated by Django 5.0.4 on 2024-04-25 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsale', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concert',
            options={'verbose_name': 'کنسرت'},
        ),
    ]
